#!/bin/bash
# This script will test all the available ciphers with the respective ports. 

# Function which define the help content.
usage(){
    echo "Usage:"
    echo "-h HELP :to get this output"
    echo "-s SERVERNAME/IP:PORT like localhost:443"
        exit
}

testcipher() {
SERVER=$DOMAIN
DELAY=1
CIPHERS=$(openssl ciphers 'ALL:eNULL' | sed -e 's/:/ /g')

echo Obtaining cipher list from $(openssl version).

for cipher in ${CIPHERS[@]}
do
echo -n Testing $cipher...
RESULT=$(echo -n | openssl s_client -cipher "$cipher" -connect $SERVER 2>&1)
if [[ "$RESULT" =~ ":error:" ]] ; then
  ERROR=$(echo -n $RESULT | cut -d':' -f6)
  echo NO \($ERROR\)
else
  if [[ "$RESULT" =~ "Cipher is ${CIPHER}" || "$RESULT" =~ "Cipher    :" ]] ; then
    echo YES
  else
    echo UNKNOWN RESPONSE
    echo $RESULT
  fi
fi
sleep $DELAY
done
}

# Main function 
# If the script didn't got any argument then it will call the usage function to guide to provide the arguments.
if [ $# = 0 ]; then
  usage
fi


while getopts "s:h:" input; do
  case $input in
    h) usage ; exit ;;
    s) DOMAIN=$OPTARG;
	   testcipher;
       exit ;;
  esac
done
